// Ranking, configuration
//
// All race data comes from static JSON files generated by
// scripts/update-data.mjs (GitHub Actions refreshes them daily) and served
// from the data/ folder next to this site.
//
// DATA_BASE: where the JSON lives, relative to the ranking page.
// Site at  <user>.github.io/mediakit/ranking/  with data in /mediakit/data/
// resolves to  <user>.github.io/mediakit/data/. Use a full URL instead if the
// data is hosted elsewhere (e.g. another repo's Pages URL).
const DATA_BASE = "../data/";

// Default competition in the dropdown (the index.json slug), used when the
// visitor has no saved selection.
const COMPETITION = "dutch-nationals";

// The dropdown lists exactly what index.json contains: the competition JSON
// files the export script wrote. data/manual-events.json is not in the index
// and is never listed. Blacklisting happens in the export script, so nothing
// to filter here.
